Creating an authentication service.
PNikitsin/OnlineStore pull request #2
Opened 2023-08-02 07:07 UTC by PNikitsin

2023-08-07 22:58 UTC, Y45K0VL3V requested changes

2023-08-07 22:58 UTC, Y45K0VL3V commented on IdentityService.Application/Services/UserService.cs
> +            if (result.Succeeded)
Maybe just invert "if" statement and alert some error, when user is not created

2023-08-07 22:58 UTC, Y45K0VL3V commented on IdentityService.Web/Program.cs
> +builder.Services.AddSwaggerGen();
Try to separate some DI registration with extension methods

2023-08-07 22:58 UTC, Y45K0VL3V commented on IdentityService.Application/DTOs/LoginUserDto.cs
> +        [Required]
Explore fluent validation

2023-08-11 15:19 UTC, gfady approved these changes

2023-08-13 21:59 UTC, merged